### ISSUE TITLE
dim function is not yet implemented for vector, vector space , affine space and inner product space

### ISSUE THREAD

**Issue by Guitang-Lan** [DarrenGZY/LFLA#17]

**Comment by cqian** [comment]
Done in vector space, affine space. How is the dimension in inner product space, the number of vectors or dimension of the matrix? @Guitang-Lan 
Dim for vector and matrix is implemented in Core.py powered  by numpy array.

**Comment by Guitang-Lan** [comment]
The number of vectors and the row or the column dimension of matrix should coincide.

**Comment by DarrenGZY** [comment]
complier works of for dim functions now. Results of dim functions need further check.

**Comment by Guitang-Lan** [comment]
@DarrenGZY  Have you update the file, I still can not pass the inspace_dim.la test
